#! /bin/sh
### BEGIN INIT INFO
# Provides:          quanser
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO, PWM, SPI for the final project
# Description:       Configures GPIO, PWM, SPI for the final project
### END INIT INFO

case "$1" in
    start|restart|force-reload)

	########################################################
	#######
	#######		vanila
 	#######		  _____ _____ _____ ____
 	#######		 / ____|  __ \_   _/ __ \
 	#######		| |  __| |__) || || |  | |
 	#######		| | |_ |  ___/ | || |  | |
 	#######		| |__| | |    _| || |__| |
 	#######		 \_____|_|   |_____\____/
	#######
	########################################################

	#######		 ___ ___ ___
	#######		|_ _/ _ \_  )
	#######		 | | (_) / /
	#######		|___\___/___|
 	#######
 	#######		ENABLE signal for REVERSE (R_PWM) pin in the H-Bridge
 	#######
   	# IO2 = gpio13
	if [ ! -d /sys/class/gpio/gpio13 ] ; then
	    echo -n "13" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio13/direction
	chgrp gpio /sys/class/gpio/gpio13/value
	chmod g+rw /sys/class/gpio/gpio13/value
	chgrp gpio /sys/class/gpio/gpio13/edge
	chmod g+rw /sys/class/gpio/gpio13/edge

	# gpio34 = 0 => IO2 = out
	if [ ! -d /sys/class/gpio/gpio34 ] ; then
	    echo -n "34" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio34/direction
	echo -n "0" > /sys/class/gpio/gpio34/value

	# gpio35 = in = no pull resistor
	if [ ! -d /sys/class/gpio/gpio35 ] ; then
	    echo -n "35" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio35/direction

	#gpio77 = 0 = mux
	if [ ! -d /sys/class/gpio/gpio77 ] ; then
		echo -n "77" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio77/value



	#######		 ___ ___  _ _
	#######		|_ _/ _ \| | |
	#######		 | | (_) |_  _|
	#######		|___\___/  |_|
 	#######
 	#######		ENABLE signal for FORWARD (L_PWM) pin in the H-Bridge
 	#######
   	# IO4 = gpio6
	if [ ! -d /sys/class/gpio/gpio6 ] ; then
	    echo -n "6" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio6/direction
	chgrp gpio /sys/class/gpio/gpio6/value
	chmod g+rw /sys/class/gpio/gpio6/value
	chgrp gpio /sys/class/gpio/gpio6/edge
	chmod g+rw /sys/class/gpio/gpio6/edge

	# gpio36 = 0 => IO4 = out
	if [ ! -d /sys/class/gpio/gpio36 ] ; then
	    echo -n "36" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio36/direction
	echo -n "0" > /sys/class/gpio/gpio36/value

	# gpio37 = in = no pull resistor
	if [ ! -d /sys/class/gpio/gpio37 ] ; then
	    echo -n "37" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio37/direction


	########################################################
	#######
 	#######      _______          ____  __
 	#######     |  __ \ \        / /  \/  |
 	#######     | |__) \ \  /\  / /| \  / |
 	#######     |  ___/ \ \/  \/ / | |\/| |
 	#######     | |      \  /\  /  | |  | |
 	#######     |_|       \/  \/   |_|  |_|
 	#######		and associated pins
	#######
	########################################################

 	####### 	 ___ ___ ____
 	####### 	|_ _/ _ \__ /
 	####### 	 | | (_) |_ \
 	####### 	|___\___/___/
 	#######
 	#######		PWM port connects to the H-Bridge to drive the motor signal
 	#######
	if [ ! -d /sys/class/pwm/pwmchip0/pwm1 ] ; then
	    echo -n "1" > /sys/class/pwm/pwmchip0/export
	fi
	chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
	chmod g+rw /sys/class/pwm/pwmchip0/device/pwm_period
	chgrp pwm /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	chmod g+rw /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	chgrp pwm /sys/class/pwm/pwmchip0/pwm1/enable
	chmod g+rw /sys/class/pwm/pwmchip0/pwm1/enable

    # gpio16 = 0 = out
	if [ ! -d /sys/class/gpio/gpio16 ] ; then
	    echo -n "16" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio16/direction
	echo -n "0" > /sys/class/gpio/gpio16/value

    # gpio17 = in = no pull resistor
	if [ ! -d /sys/class/gpio/gpio17 ] ; then
	    echo -n "17" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio17/direction

    # gpio76 = 0 = mux
	if [ ! -d /sys/class/gpio/gpio76 ] ; then
	    echo -n "76" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio76/value

    # gpio64 = 1 = mux
	if [ ! -d /sys/class/gpio/gpio64 ] ; then
	    echo -n "64" > /sys/class/gpio/export
	fi
	echo -n "1" > /sys/class/gpio/gpio64/value

	########################################################
	#######
 	#######		  _____ _____ _____
 	#######		 / ____|  __ \_   _|
 	#######		| (___ | |__) || |
 	#######		 \___ \|  ___/ | |
 	#######		 ____) | |    _| |_
 	#######		|_____/|_|   |_____|
 	#######		and associated pins
	#######
	########################################################



	# gpio49 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio49 ] ; then
	    echo -n "49" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio49/direction

	# gpio51 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio51 ] ; then
	    echo -n "51" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio51/direction

	# gpio53 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio53 ] ; then
	    echo -n "53" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio53/direction

	# gpio55 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio55 ] ; then
	    echo -n "55" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio55/direction

        for i in {0..3} ; do
        	chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage"$i"_scale
        	chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage"$i"_scale

        	chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage"$i"_en
		chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage"$i"_en
        done;

	chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
	chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en

        chgrp adc /sys/bus/iio/devices/iio:device0/buffer/enable
        chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/enable
        chgrp adc /sys/bus/iio/devices/iio:device0/buffer/length
	chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/length

        modprobe iio-trig-sysfs
        echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/add_trigger

        chgrp adc /sys/bus/iio/devices/trigger0/trigger_now
	chmod g+w /sys/bus/iio/devices/trigger0/trigger_now

	modprobe iio-trig-hrtimer
       	echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/add_trigger

        chgrp adc /sys/bus/iio/devices/trigger1/frequency
        chmod g+rw /sys/bus/iio/devices/trigger1/frequency

        chgrp adc /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	chmod g+rw /sys/bus/iio/devices/iio:device0/trigger/current_trigger

	chgrp adc /dev/iio:device0
	chmod g+r /dev/iio:device0
    	;;
    stop)
	echo "\n" > /sys/bus/iio/devices/iio:device0/trigger/current_trigger

	echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/remove_trigger
	rmmod iio-trig-hrtimer
	echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/remove_trigger
	rmmod iio-trig-sysfs

	echo -n "49" > /sys/class/gpio/unexport
	echo -n "51" > /sys/class/gpio/unexport
	echo -n "53" > /sys/class/gpio/unexport
	echo -n "55" > /sys/class/gpio/unexport
	;;
    status)
    	cat /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
