#! /bin/sh
### BEGIN INIT INFO
# Provides:          quanser
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO, PWM, SPI for the final project
# Description:       Configures GPIO, PWM, SPI for the final project
### END INIT INFO

case "$1" in
    start|restart|force-reload)

	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	#x
	#x		vanila
 	#x		  _____ _____ _____ ____
 	#x		 / ____|  __ \_   _/ __ \
 	#x		| |  __| |__) || || |  | |
 	#x		| | |_ |  ___/ | || |  | |
 	#x		| |__| | |    _| || |__| |
 	#x		 \_____|_|   |_____\____/
	#x
	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-

	#######		 ___ ___ ___
	#######		|_ _/ _ \_  )
	#######		 | | (_) / /
	#######		|___\___/___|
 	#######
 	#######		ENABLE signal for REVERSE (R_PWM) pin in the H-Bridge
 	#######
   	# IO2 = gpio13
	if [ ! -d /sys/class/gpio/gpio13 ] ; then
	    echo -n "13" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio13/direction
	chgrp gpio /sys/class/gpio/gpio13/value
	chmod g+rw /sys/class/gpio/gpio13/value
	chgrp gpio /sys/class/gpio/gpio13/edge
	chmod g+rw /sys/class/gpio/gpio13/edge

	# gpio34 = 0 => IO2 = out
	if [ ! -d /sys/class/gpio/gpio34 ] ; then
	    echo -n "34" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio34/direction
	echo -n "0" > /sys/class/gpio/gpio34/value

	# gpio35 = in = no pull resistor
	if [ ! -d /sys/class/gpio/gpio35 ] ; then
	    echo -n "35" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio35/direction

	#gpio77 = 0 = mux
	if [ ! -d /sys/class/gpio/gpio77 ] ; then
		echo -n "77" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio77/value

	#######		 ___ ___  _ _
	#######		|_ _/ _ \| | |
	#######		 | | (_) |_  _|
	#######		|___\___/  |_|
 	#######
 	#######		ENABLE signal for FORWARD (L_PWM) pin in the H-Bridge
 	#######
   	# IO4 = gpio6
	if [ ! -d /sys/class/gpio/gpio6 ] ; then
	    echo -n "6" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio6/direction
	chgrp gpio /sys/class/gpio/gpio6/value
	chmod g+rw /sys/class/gpio/gpio6/value
	chgrp gpio /sys/class/gpio/gpio6/edge
	chmod g+rw /sys/class/gpio/gpio6/edge

	# gpio36 = 0 => IO4 = out
	if [ ! -d /sys/class/gpio/gpio36 ] ; then
	    echo -n "36" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio36/direction
	echo -n "0" > /sys/class/gpio/gpio36/value

	# gpio37 = in = no pull resistor
	if [ ! -d /sys/class/gpio/gpio37 ] ; then
	    echo -n "37" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio37/direction

	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	#x
 	#x      _______          ____  __
 	#x     |  __ \ \        / /  \/  |
 	#x     | |__) \ \  /\  / /| \  / |
 	#x     |  ___/ \ \/  \/ / | |\/| |
 	#x     | |      \  /\  /  | |  | |
 	#x     |_|       \/  \/   |_|  |_|
 	#x		and associated pins
	#x
	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-

 	####### 	 ___ ___ ____
 	####### 	|_ _/ _ \__ /
 	####### 	 | | (_) |_ \
 	####### 	|___\___/___/
 	#######
 	#######		PWM port connects to the H-Bridge to drive the motor signal
 	#######
	if [ ! -d /sys/class/pwm/pwmchip0/pwm1 ] ; then
	    echo -n "1" > /sys/class/pwm/pwmchip0/export
	fi
	chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
	chmod g+rw /sys/class/pwm/pwmchip0/device/pwm_period
	chgrp pwm /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	chmod g+rw /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	chgrp pwm /sys/class/pwm/pwmchip0/pwm1/enable
	chmod g+rw /sys/class/pwm/pwmchip0/pwm1/enable

    # gpio16 = 0 = out
	if [ ! -d /sys/class/gpio/gpio16 ] ; then
	    echo -n "16" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio16/direction
	echo -n "0" > /sys/class/gpio/gpio16/value

    # gpio17 = in = no pull resistor
	if [ ! -d /sys/class/gpio/gpio17 ] ; then
	    echo -n "17" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio17/direction

    # gpio76 = 0 = mux
	if [ ! -d /sys/class/gpio/gpio76 ] ; then
	    echo -n "76" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio76/value

    # gpio64 = 1 = mux
	if [ ! -d /sys/class/gpio/gpio64 ] ; then
	    echo -n "64" > /sys/class/gpio/export
	fi
	echo -n "1" > /sys/class/gpio/gpio64/value

	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	#x
 	#x		  _____ _____ _____
 	#x		 / ____|  __ \_   _|
 	#x		| (___ | |__) || |
 	#x		 \___ \|  ___/ | |
 	#x		 ____) | |    _| |_
 	#x		|_____/|_|   |_____|
 	#x		and associated pins
	#x
	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-

    	;;
    stop)
	
	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	# GPIO
	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	
	# IO2
	echo -n "1" > /sys/class/gpio/gpio34/value
	echo -n "13" > /sys/class/gpio/unexport
	echo -n "34" > /sys/class/gpio/unexport
	echo -n "35" > /sys/class/gpio/unexport
	echo -n "77" > /sys/class/gpio/unexport

	# IO4
	echo -n "1" > /sys/class/gpio/gpio36/value
	echo -n "6" > /sys/class/gpio/unexport
	echo -n "36" > /sys/class/gpio/unexport
	echo -n "37" > /sys/class/gpio/unexport
	
	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	# PWM
	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	
	# IO3
	echo -n "0" > /sys/class/pwm/pwmchip0/pwm1/enable
	echo -n "1" > /sys/class/gpio/gpio16/value
	echo -n "76" > /sys/class/gpio/unexport
    echo -n "64" > /sys/class/gpio/unexport
	echo -n "17" > /sys/class/gpio/unexport
	echo -n "16" > /sys/class/gpio/unexport
	echo -n "1" > /sys/class/pwm/pwmchip0/unexport

	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	# SPI
	#-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	# gpio13
	# gpio16
	# gpio17
	# gpio34
	# gpio35
	# gpio36
	# gpio37
	# gpio6
	# gpio64
	# gpio76
	# gpio77
	;;
    status)
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
