#! /bin/sh
### BEGIN INIT INFO
# Provides:          quanserio
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO, PWM, SPI for the final project
# Description:       Configures GPIO, PWM, SPI for the final project
### END INIT INFO

case "$1" in
    start|restart|force-reload)

    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    #x
    #x      vanila
    #x        _____ _____ _____ ____
    #x       / ____|  __ \_   _/ __ \
    #x      | |  __| |__) || || |  | |
    #x      | | |_ |  ___/ | || |  | |
    #x      | |__| | |    _| || |__| |
    #x       \_____|_|   |_____\____/
    #x
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-

    #######      ___ ___  _ 
    #######     |_ _/ _ \/ |
    #######      | | (_) | |
    #######     |___\___/|_|
    #######            
    #######     LIMIT_1 signal from quanser (final de curso)
    #######
    # IO1 = gpio12
    if [ ! -d /sys/class/gpio/gpio12 ] ; then
        echo -n "12" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio12/direction
    echo -n "1" > /sys/class/gpio/gpio12/value
    chgrp gpio /sys/class/gpio/gpio12/value
    chmod g+rw /sys/class/gpio/gpio12/value
    chgrp gpio /sys/class/gpio/gpio12/edge
    chmod g+rw /sys/class/gpio/gpio12/edge

    
    if [ ! -d /sys/class/gpio/gpio28 ] ; then
        echo -n "28" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio28/direction
    echo -n "1" > /sys/class/gpio/gpio28/value
    
    # pull-up resistor
    if [ ! -d /sys/class/gpio/gpio29 ] ; then
        echo -n "29" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio29/direction
    echo -n "1" > /sys/class/gpio/gpio29/value
    
    # mux
    if [ ! -d /sys/class/gpio/gpio45 ] ; then
        echo -n "45" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio45/direction
    echo -n "0" > /sys/class/gpio/gpio45/value

    #######      ___ ___ ___ 
    #######     |_ _/ _ \_  )
    #######      | | (_) / / 
    #######     |___\___/___|
    #######                  
    #######     LIMIT_2 signal from quanser (final de curso)
    #######
    # IO2 = gpio13
    if [ ! -d /sys/class/gpio/gpio13 ] ; then
        echo -n "13" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio13/direction
    echo -n "1" > /sys/class/gpio/gpio13/value
    chgrp gpio /sys/class/gpio/gpio13/value
    chmod g+rw /sys/class/gpio/gpio13/value
    chgrp gpio /sys/class/gpio/gpio13/edge
    chmod g+rw /sys/class/gpio/gpio13/edge

    
    if [ ! -d /sys/class/gpio/gpio34 ] ; then
        echo -n "34" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio34/direction
    echo -n "1" > /sys/class/gpio/gpio34/value
    
    # pull-up resistor
    if [ ! -d /sys/class/gpio/gpio35 ] ; then
        echo -n "35" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio35/direction
    echo -n "1" > /sys/class/gpio/gpio35/value
    
    # mux
    if [ ! -d /sys/class/gpio/gpio77 ] ; then
        echo -n "77" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio77/direction
    echo -n "0" > /sys/class/gpio/gpio77/value
    
    #######      ___ ___ ____
    #######     |_ _/ _ \__ /
    #######      | | (_) |_ \
    #######     |___\___/___/
    #######
    #######     R_EN Signal
    #######

    # gpio62 = 0 = out
    if [ ! -d /sys/class/gpio/gpio62 ] ; then
        echo -n "62" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio62/direction

    chgrp gpio /sys/class/gpio/gpio62/value
    chmod g+rw /sys/class/gpio/gpio62/value
    
    # # gpio16 = 0 = out
    # if [ ! -d /sys/class/gpio/gpio16 ] ; then
    #     echo -n "16" > /sys/class/gpio/export
    # fi
    # echo -n "out" > /sys/class/gpio/gpio16/direction
    # echo -n "0" > /sys/class/gpio/gpio16/value

    # # gpio17 = in = no pull resistor
    # if [ ! -d /sys/class/gpio/gpio17 ] ; then
    #     echo -n "17" > /sys/class/gpio/export
    # fi
    # echo -n "in" > /sys/class/gpio/gpio17/direction

    # gpio76 = 0 = mux
    if [ ! -d /sys/class/gpio/gpio76 ] ; then
        echo -n "76" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio76/direction
    echo -n "0" > /sys/class/gpio/gpio76/value

    # gpio64 = 0 = mux
    if [ ! -d /sys/class/gpio/gpio64 ] ; then
        echo -n "64" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio64/direction
    echo -n "0" > /sys/class/gpio/gpio64/value

    #######      ___ ___  _ _
    #######     |_ _/ _ \| | |
    #######      | | (_) |_  _|
    #######     |___\___/  |_|
    #######
    #######     L_EN Signal
    #######
    # IO4 = gpio6
    if [ ! -d /sys/class/gpio/gpio6 ] ; then
        echo -n "6" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio6/direction
    chgrp gpio /sys/class/gpio/gpio6/value
    chmod g+rw /sys/class/gpio/gpio6/value
    chgrp gpio /sys/class/gpio/gpio6/edge
    chmod g+rw /sys/class/gpio/gpio6/edge

    # gpio36 = 0 => IO4 = out
    if [ ! -d /sys/class/gpio/gpio36 ] ; then
        echo -n "36" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio36/direction
    echo -n "0" > /sys/class/gpio/gpio36/value

    # gpio37 = in = no pull resistor
    if [ ! -d /sys/class/gpio/gpio37 ] ; then
        echo -n "37" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio37/direction

    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    #x
    #x      _______          ____  __
    #x     |  __ \ \        / /  \/  |
    #x     | |__) \ \  /\  / /| \  / |
    #x     |  ___/ \ \/  \/ / | |\/| |
    #x     | |      \  /\  /  | |  | |
    #x     |_|       \/  \/   |_|  |_|
    #x      and associated pins
    #x
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-

    #######      ___ ___  ___ 
    #######     |_ _/ _ \| __|
    #######      | | (_) |__ \
    #######     |___\___/|___/
    #######
    #######     R_PWM Signal
    #######
    if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
        echo -n "3" > /sys/class/pwm/pwmchip0/export
    fi
    chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
    chmod g+rw /sys/class/pwm/pwmchip0/device/pwm_period
    chgrp pwm /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    chmod g+rw /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    chgrp pwm /sys/class/pwm/pwmchip0/pwm3/enable
    chmod g+rw /sys/class/pwm/pwmchip0/pwm3/enable

    
    # gpio18 = 0 = out
    if [ ! -d /sys/class/gpio/gpio18 ] ; then
        echo -n "18" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio18/direction
    echo -n "0" > /sys/class/gpio/gpio18/value

    # gpio19 = in = no pull resistor
    if [ ! -d /sys/class/gpio/gpio19 ] ; then
        echo -n "19" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio19/direction

    # gpio66 = 1 = mux
    if [ ! -d /sys/class/gpio/gpio66 ] ; then
        echo -n "66" > /sys/class/gpio/export
    fi
    echo -n "1" > /sys/class/gpio/gpio66/value

    #######      ___ ___   __ 
    #######     |_ _/ _ \ / / 
    #######      | | (_) / _ \
    #######     |___\___/\___/
    #######                   
    #######     L_PWM Signal
    #######
    if [ ! -d /sys/class/pwm/pwmchip0/pwm5 ] ; then
        echo -n "5" > /sys/class/pwm/pwmchip0/export
    fi
    chgrp pwm /sys/class/pwm/pwmchip0/pwm5/duty_cycle
    chmod g+rw /sys/class/pwm/pwmchip0/pwm5/duty_cycle
    chgrp pwm /sys/class/pwm/pwmchip0/pwm5/enable
    chmod g+rw /sys/class/pwm/pwmchip0/pwm5/enable

    
    # gpio20 = 0 = out
    if [ ! -d /sys/class/gpio/gpio20 ] ; then
        echo -n "20" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio20/direction
    echo -n "0" > /sys/class/gpio/gpio20/value

    # gpio21 = in = no pull resistor
    if [ ! -d /sys/class/gpio/gpio21 ] ; then
        echo -n "21" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio21/direction

    # gpio68 = 1 = mux
    if [ ! -d /sys/class/gpio/gpio68 ] ; then
        echo -n "68" > /sys/class/gpio/export
    fi
    echo -n "1" > /sys/class/gpio/gpio68/value

    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    #x
    #x        _____ _____ _____
    #x       / ____|  __ \_   _|
    #x      | (___ | |__) || |
    #x       \___ \|  ___/ | |
    #x       ____) | |    _| |_
    #x      |_____/|_|   |_____|
    #x      and associated pins
    #x
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-

    #######      ___ ___  ___ 
    #######     |_ _/ _ \/ _ \
    #######      | | (_) \_, /
    #######     |___\___/ /_/ 
    #######                   
    #######     SPI SS pin (digital write)
    #######
    # IO9 = gpio4
    if [ ! -d /sys/class/gpio/gpio4 ] ; then
        echo -n "4" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio4/direction
    chgrp spi /sys/class/gpio/gpio4/value
    chmod g+rw /sys/class/gpio/gpio4/value

    # gpio22 = 0 = out
    if [ ! -d /sys/class/gpio/gpio22 ] ; then
        echo -n "22" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio22/direction
    echo -n "0" > /sys/class/gpio/gpio22/value

    # gpio23 = 1 = pull high
    if [ ! -d /sys/class/gpio/gpio23 ] ; then
        echo -n "23" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio23/direction
    echo -n "1" > /sys/class/gpio/gpio23/value

    # gpio70 = 0 (low) = mux
    if [ ! -d /sys/class/gpio/gpio70 ] ; then
        echo -n "70" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio70/direction
    echo -n "0" > /sys/class/gpio/gpio70/value

    #######      ___ ___  _  __  
    #######     |_ _/ _ \/ |/  \ 
    #######      | | (_) | | () |
    #######     |___\___/|_|\__/ 
    #######                      
    #######     LS7366 enable pin (digital write)
    #######
    # IO10 = gpio10
    if [ ! -d /sys/class/gpio/gpio10 ] ; then
        echo -n "10" > /sys/class/gpio/export
    fi          
    echo -n "out" > /sys/class/gpio/gpio10/direction
    # echo -n "1" > /sys/class/gpio/gpio10/value
    chgrp spi /sys/class/gpio/gpio10/value
    chmod g+rw /sys/class/gpio/gpio10/value

    # gpio26 = 0 = out
    if [ ! -d /sys/class/gpio/gpio26 ] ; then
        echo -n "26" > /sys/class/gpio/export
    fi          
    echo -n "out" > /sys/class/gpio/gpio26/direction
    echo -n "0" > /sys/class/gpio/gpio26/value
    
    # gpio27 = 1 = pull up resistor
    if [ ! -d /sys/class/gpio/gpio27 ] ; then
        echo -n "27" > /sys/class/gpio/export
    fi          
    echo -n "out" > /sys/class/gpio/gpio27/direction
    echo -n "1" > /sys/class/gpio/gpio27/value
    
    # gpio74 = 0 (low) = mux
    if [ ! -d /sys/class/gpio/gpio74 ] ; then
        echo -n "74" > /sys/class/gpio/export
    fi          
    echo -n "out" > /sys/class/gpio/gpio74/direction
    echo -n "0" > /sys/class/gpio/gpio74/value


    #######      ___ ___  _ _ 
    #######     |_ _/ _ \/ / |
    #######      | | (_) | | |
    #######     |___\___/|_|_|
    #######               
    #######     SPI MOSI pin  
    #######
    # IO11 -> SPI MOSI = gpio24
    if [ ! -d /sys/class/gpio/gpio24 ] ; then
        echo -n "24" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio24/direction
    echo -n "0" > /sys/class/gpio/gpio24/value
    
    # gpio25 = in = no pull resistor
    if [ ! -d /sys/class/gpio/gpio25 ] ; then
        echo -n "25" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio25/direction
    
    # gpio44 = 1 (high) = mux
    if [ ! -d /sys/class/gpio/gpio44 ] ; then
        echo -n "44" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio44/direction
    echo -n "1" > /sys/class/gpio/gpio44/value
    
    # gpio72 = 0 (low) = mux
    if [ ! -d /sys/class/gpio/gpio72 ] ; then
        echo -n "72" > /sys/class/gpio/export
    fi
    echo -n "0" > /sys/class/gpio/gpio72/value

    #######      ___ ___  _ ___ 
    #######     |_ _/ _ \/ |_  )
    #######      | | (_) | |/ / 
    #######     |___\___/|_/___|
    #######             
    #######     SPI MISO pin  
    #######
    # IO12 -> SPI MISO = gpio42
    if [ ! -d /sys/class/gpio/gpio42 ] ; then
        echo -n "42" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio42/direction
    echo -n "1" > /sys/class/gpio/gpio42/value
    
    # gpio43 = in = no pull resistor
    if [ ! -d /sys/class/gpio/gpio43 ] ; then
        echo -n "43" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio43/direction

    #######      ___ ___  _ ____
    #######     |_ _/ _ \/ |__ /
    #######      | | (_) | ||_ \
    #######     |___\___/|_|___/
    #######                     
    #######     SPI SCK pin  
    #######
    # IO13 -> SCK = gpio30
    if [ ! -d /sys/class/gpio/gpio30 ] ; then
        echo -n "30" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio30/direction
    echo -n "0" > /sys/class/gpio/gpio30/value
    
    # gpio31 = 0 = pull down
    if [ ! -d /sys/class/gpio/gpio31 ] ; then
        echo -n "31" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio31/direction
    echo -n "0" > /sys/class/gpio/gpio31/value
    
    # gpio36 = 1 (high) = mux
    if [ ! -d /sys/class/gpio/gpio46 ] ; then
        echo -n "46" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio46/direction
    echo -n "1" > /sys/class/gpio/gpio46/value

    chgrp spi /dev/spidev1.0
    chmod g+rw /dev/spidev1.0

        ;;
    stop)
    
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    # GPIO
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    
    # IO2
    echo -n "1" > /sys/class/gpio/gpio34/value
    echo -n "13" > /sys/class/gpio/unexport
    echo -n "34" > /sys/class/gpio/unexport
    echo -n "35" > /sys/class/gpio/unexport
    echo -n "77" > /sys/class/gpio/unexport

    # IO4
    echo -n "1" > /sys/class/gpio/gpio36/value
    echo -n "6" > /sys/class/gpio/unexport
    echo -n "36" > /sys/class/gpio/unexport
    echo -n "37" > /sys/class/gpio/unexport

    # IO5

    # IO6
    
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    # PWM
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    
    # IO3
    echo -n "0" > /sys/class/pwm/pwmchip0/pwm1/enable
    echo -n "1" > /sys/class/gpio/gpio16/value
    echo -n "76" > /sys/class/gpio/unexport
    echo -n "64" > /sys/class/gpio/unexport
    echo -n "17" > /sys/class/gpio/unexport
    echo -n "16" > /sys/class/gpio/unexport
    echo -n "1" > /sys/class/pwm/pwmchip0/unexport

    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    # SPI
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    
    # IO9
    echo -n "4" > /sys/class/gpio/unexport
    echo -n "1" > /sys/class/gpio/gpio22/value
    echo -n "22" > /sys/class/gpio/unexport
    echo -n "23" > /sys/class/gpio/unexport
    echo -n "70" > /sys/class/gpio/unexport
    
    # IO10
    echo -n "10" > /sys/class/gpio/unexport
    echo -n "1" > /sys/class/gpio/gpio26/value
    echo -n "26" > /sys/class/gpio/unexport
    echo -n "27" > /sys/class/gpio/unexport
    echo -n "74" > /sys/class/gpio/unexport
    
    # IO11
    echo -n "1" > /sys/class/gpio/gpio24/value
    echo -n "24" > /sys/class/gpio/unexport
    echo -n "25" > /sys/class/gpio/unexport
    echo -n "44" > /sys/class/gpio/unexport
    echo -n "72" > /sys/class/gpio/unexport
    
    # IO12
    echo -n "42" > /sys/class/gpio/unexport
    echo -n "43" > /sys/class/gpio/unexport
    
    # IO13
    echo -n "1" > /sys/class/gpio/gpio30/value
    echo -n "30" > /sys/class/gpio/unexport
    echo -n "31" > /sys/class/gpio/unexport
    echo -n "46" > /sys/class/gpio/unexport

    ;;
    status)
    ;;
    *)
    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
