#! /bin/sh
### BEGIN INIT INFO
# Provides:          provaio
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO/ADC for final exam
# Description:       Configures GPIO/ADC for final exam
### END INIT INFO
# Copyright (c) 2019 Gustavo Santana, Lúcio Franco
case "$1" in
    start|restart|force-reload)

    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    #x
    #x        _____ _____ _____ ____
    #x       / ____|  __ \_   _/ __ \
    #x      | |  __| |__) || || |  | |
    #x      | | |_ |  ___/ | || |  | |
    #x      | |__| | |    _| || |__| |
    #x       \_____|_|   |_____\____/
    #x
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-

	# gpio49 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio49 ] ; then
	    echo -n "49" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio49/direction
        
	chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
	chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale
	
	chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage0_en
	chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage0_en

	chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
	chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
	
    chgrp adc /sys/bus/iio/devices/iio:device0/buffer/enable
    chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/enable
    chgrp adc /sys/bus/iio/devices/iio:device0/buffer/length
	chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/length
	
 #    modprobe iio-trig-sysfs
 #    echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/add_trigger
    
 #    chgrp adc /sys/bus/iio/devices/trigger0/trigger_now
	# chmod g+w /sys/bus/iio/devices/trigger0/trigger_now
	
	modprobe iio-trig-hrtimer
   	echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/add_trigger
    
    chgrp adc /sys/bus/iio/devices/trigger0/frequency
    chmod g+rw /sys/bus/iio/devices/trigger0/frequency
    
    chgrp adc /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	chmod g+rw /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	
	chgrp adc /dev/iio:device0
	chmod g+r /dev/iio:device0
    	;;
    stop)
	echo "\n" > /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	
	echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/remove_trigger
	rmmod iio-trig-hrtimer
	echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/remove_trigger
	rmmod iio-trig-sysfs
	
	echo -n "49" > /sys/class/gpio/unexport
	echo -n "51" > /sys/class/gpio/unexport
	echo -n "53" > /sys/class/gpio/unexport
	echo -n "55" > /sys/class/gpio/unexport

        ;;
    stop)

    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
    # GPIO
    #-~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~--~.~-
	echo "\n" > /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	
	echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/remove_trigger
	rmmod iio-trig-hrtimer
	echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/remove_trigger
	rmmod iio-trig-sysfs
	
	echo -n "49" > /sys/class/gpio/unexport
	echo -n "51" > /sys/class/gpio/unexport
	echo -n "53" > /sys/class/gpio/unexport
	echo -n "55" > /sys/class/gpio/unexport

    ;;
    status)
	cat /sys/bus/iio/devices/iio:device0/trigger/current_trigger
    ;;
    *)
    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
